/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.someip.deployment'
*******************************************************************************/
package org.genivi.commonapi.someip;

import java.util.List;
import java.util.ArrayList;
import org.eclipse.emf.ecore.EObject;
import org.franca.core.franca.FInterface;
import org.franca.core.franca.FField;
import org.franca.core.franca.FArgument;
import org.franca.core.franca.FMethod;
import org.franca.core.franca.FEnumerationType;
import org.franca.core.franca.FAttribute;
import org.franca.core.franca.FBroadcast;
import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.someip.deployment' specification
 */		
public class DeploymentInterfacePropertyAccessor
	extends org.genivi.commonapi.core.DeploymentInterfacePropertyAccessor
{
	
	private FDeployedInterface target;

	public DeploymentInterfacePropertyAccessor (FDeployedInterface target) {
		super(target);
		this.target = target;
	}
	
	public Integer getSomeIpServiceID (FInterface obj) {
		return target.getInteger(obj, "SomeIpServiceID");
	}
	
	public List<Integer> getSomeIpEventGroups (FInterface obj) {
		return target.getIntegerArray(obj, "SomeIpEventGroups");
	}
	
	public Integer getSomeIpGetterID (FAttribute obj) {
		return target.getInteger(obj, "SomeIpGetterID");
	}
	
	public Boolean getSomeIpGetterReliable (FAttribute obj) {
		return target.getBoolean(obj, "SomeIpGetterReliable");
	}
	
	public Integer getSomeIpGetterPriority (FAttribute obj) {
		return target.getInteger(obj, "SomeIpGetterPriority");
	}
	
	public Integer getSomeIpSetterID (FAttribute obj) {
		return target.getInteger(obj, "SomeIpSetterID");
	}
	
	public Boolean getSomeIpSetterReliable (FAttribute obj) {
		return target.getBoolean(obj, "SomeIpSetterReliable");
	}
	
	public Integer getSomeIpSetterPriority (FAttribute obj) {
		return target.getInteger(obj, "SomeIpSetterPriority");
	}
	
	public Integer getSomeIpNotifierID (FAttribute obj) {
		return target.getInteger(obj, "SomeIpNotifierID");
	}
	
	public Boolean getSomeIpNotifierReliable (FAttribute obj) {
		return target.getBoolean(obj, "SomeIpNotifierReliable");
	}
	
	public Integer getSomeIpNotifierPriority (FAttribute obj) {
		return target.getInteger(obj, "SomeIpNotifierPriority");
	}
	
	public Boolean getSomeIpNotifierMulticast (FAttribute obj) {
		return target.getBoolean(obj, "SomeIpNotifierMulticast");
	}
	
	public List<Integer> getSomeIpEventGroups (FAttribute obj) {
		return target.getIntegerArray(obj, "SomeIpEventGroups");
	}
	
	public Integer getSomeIpMethodID (FMethod obj) {
		return target.getInteger(obj, "SomeIpMethodID");
	}
	
	public Boolean getSomeIpReliable (FMethod obj) {
		return target.getBoolean(obj, "SomeIpReliable");
	}
	
	public Integer getSomeIpPriority (FMethod obj) {
		return target.getInteger(obj, "SomeIpPriority");
	}
	
	public enum SomeIpErrorCoding {
		Header
	}
	public SomeIpErrorCoding getSomeIpErrorCoding (FMethod obj) {
		String e = target.getEnum(obj, "SomeIpErrorCoding");
		if (e==null) return null;
		return convertSomeIpErrorCoding(e);
	}
	private SomeIpErrorCoding convertSomeIpErrorCoding (String val) {
		if (val.equals("Header"))
			return SomeIpErrorCoding.Header;
		return null;
	}
	
	public Integer getSomeIpEventID (FBroadcast obj) {
		return target.getInteger(obj, "SomeIpEventID");
	}
	
	public Boolean getSomeIpReliable (FBroadcast obj) {
		return target.getBoolean(obj, "SomeIpReliable");
	}
	
	public Integer getSomeIpPriority (FBroadcast obj) {
		return target.getInteger(obj, "SomeIpPriority");
	}
	
	public Boolean getSomeIpMulticast (FBroadcast obj) {
		return target.getBoolean(obj, "SomeIpMulticast");
	}
	
	public List<Integer> getSomeIpEventGroups (FBroadcast obj) {
		return target.getIntegerArray(obj, "SomeIpEventGroups");
	}
	
	public Integer getSomeIpArrayMinLength (EObject obj) {
		return target.getInteger(obj, "SomeIpArrayMinLength");
	}
	
	public Integer getSomeIpArrayMaxLength (EObject obj) {
		return target.getInteger(obj, "SomeIpArrayMaxLength");
	}
	
	public Integer getSomeIpArrayLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpArrayLengthWidth");
	}
	
	public Integer getSomeIpUnionLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionLengthWidth");
	}
	
	public Integer getSomeIpUnionTypeWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionTypeWidth");
	}
	
	public Boolean getSomeIpUnionDefaultOrder (EObject obj) {
		return target.getBoolean(obj, "SomeIpUnionDefaultOrder");
	}
	
	public Integer getSomeIpUnionMaxLength (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionMaxLength");
	}
	
	public Integer getSomeIpStructLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpStructLengthWidth");
	}
	
	public Integer getSomeIpEnumWidth (FEnumerationType obj) {
		return target.getInteger(obj, "SomeIpEnumWidth");
	}
	
	public Integer getSomeIpStringLength (EObject obj) {
		return target.getInteger(obj, "SomeIpStringLength");
	}
	
	public Integer getSomeIpStringLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpStringLengthWidth");
	}
	
	public enum SomeIpStringEncoding {
		utf8, utf16le, utf16be
	}
	public SomeIpStringEncoding getSomeIpStringEncoding (EObject obj) {
		String e = target.getEnum(obj, "SomeIpStringEncoding");
		if (e==null) return null;
		return convertSomeIpStringEncoding(e);
	}
	private SomeIpStringEncoding convertSomeIpStringEncoding (String val) {
		if (val.equals("utf8"))
			return SomeIpStringEncoding.utf8; else 
		if (val.equals("utf16le"))
			return SomeIpStringEncoding.utf16le; else 
		if (val.equals("utf16be"))
			return SomeIpStringEncoding.utf16be;
		return null;
	}
	
	public Integer getSomeIpAttrArrayMinLength (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrArrayMinLength");
	}
	
	public Integer getSomeIpAttrArrayMaxLength (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrArrayMaxLength");
	}
	
	public Integer getSomeIpAttrArrayLengthWidth (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrArrayLengthWidth");
	}
	
	public Integer getSomeIpAttrUnionLengthWidth (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrUnionLengthWidth");
	}
	
	public Integer getSomeIpAttrUnionTypeWidth (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrUnionTypeWidth");
	}
	
	public Boolean getSomeIpAttrUnionDefaultOrder (FAttribute obj) {
		return target.getBoolean(obj, "SomeIpAttrUnionDefaultOrder");
	}
	
	public Integer getSomeIpAttrUnionMaxLength (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrUnionMaxLength");
	}
	
	public Integer getSomeIpAttrStructLengthWidth (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrStructLengthWidth");
	}
	
	public Integer getSomeIpAttrEnumWidth (FAttribute obj) {
		return target.getInteger(obj, "SomeIpAttrEnumWidth");
	}
	
	public Integer getSomeIpArgArrayMinLength (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgArrayMinLength");
	}
	
	public Integer getSomeIpArgArrayMaxLength (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgArrayMaxLength");
	}
	
	public Integer getSomeIpArgArrayLengthWidth (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgArrayLengthWidth");
	}
	
	public Integer getSomeIpArgUnionLengthWidth (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgUnionLengthWidth");
	}
	
	public Integer getSomeIpArgUnionTypeWidth (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgUnionTypeWidth");
	}
	
	public Boolean getSomeIpArgUnionDefaultOrder (FArgument obj) {
		return target.getBoolean(obj, "SomeIpArgUnionDefaultOrder");
	}
	
	public Integer getSomeIpArgUnionMaxLength (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgUnionMaxLength");
	}
	
	public Integer getSomeIpArgStructLengthWidth (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgStructLengthWidth");
	}
	
	public Integer getSomeIpArgEnumWidth (FArgument obj) {
		return target.getInteger(obj, "SomeIpArgEnumWidth");
	}
	
	public Integer getSomeIpStructArrayMinLength (FField obj) {
		return target.getInteger(obj, "SomeIpStructArrayMinLength");
	}
	
	public Integer getSomeIpStructArrayMaxLength (FField obj) {
		return target.getInteger(obj, "SomeIpStructArrayMaxLength");
	}
	
	public Integer getSomeIpStructArrayLengthWidth (FField obj) {
		return target.getInteger(obj, "SomeIpStructArrayLengthWidth");
	}
	
	public Integer getSomeIpStructUnionLengthWidth (FField obj) {
		return target.getInteger(obj, "SomeIpStructUnionLengthWidth");
	}
	
	public Integer getSomeIpStructUnionTypeWidth (FField obj) {
		return target.getInteger(obj, "SomeIpStructUnionTypeWidth");
	}
	
	public Boolean getSomeIpStructUnionDefaultOrder (FField obj) {
		return target.getBoolean(obj, "SomeIpStructUnionDefaultOrder");
	}
	
	public Integer getSomeIpStructUnionMaxLength (FField obj) {
		return target.getInteger(obj, "SomeIpStructUnionMaxLength");
	}
	
	public Integer getSomeIpStructStructLengthWidth (FField obj) {
		return target.getInteger(obj, "SomeIpStructStructLengthWidth");
	}
	
	public Integer getSomeIpStructEnumWidth (FField obj) {
		return target.getInteger(obj, "SomeIpStructEnumWidth");
	}
	
	public Integer getSomeIpUnionArrayMinLength (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionArrayMinLength");
	}
	
	public Integer getSomeIpUnionArrayMaxLength (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionArrayMaxLength");
	}
	
	public Integer getSomeIpUnionArrayLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionArrayLengthWidth");
	}
	
	public Integer getSomeIpUnionUnionLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionUnionLengthWidth");
	}
	
	public Integer getSomeIpUnionUnionTypeWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionUnionTypeWidth");
	}
	
	public Boolean getSomeIpUnionUnionDefaultOrder (EObject obj) {
		return target.getBoolean(obj, "SomeIpUnionUnionDefaultOrder");
	}
	
	public Integer getSomeIpUnionUnionMaxLength (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionUnionMaxLength");
	}
	
	public Integer getSomeIpUnionStructLengthWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionStructLengthWidth");
	}
	
	public Integer getSomeIpUnionEnumWidth (EObject obj) {
		return target.getInteger(obj, "SomeIpUnionEnumWidth");
	}
	
	
}
