/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.genivi.commonapi.someip.deployment'
*******************************************************************************/
package org.genivi.commonapi.someip;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.someip.deployment' specification
 *
 * @deprecated use class org.genivi.commonapi.someip.Deployment.TypeCollectionPropertyAccessor instead
 */
public class DeploymentTypeCollectionPropertyAccessor
	extends org.genivi.commonapi.someip.Deployment.TypeCollectionPropertyAccessor
	implements org.genivi.commonapi.someip.Deployment.Enums
{
	public DeploymentTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
