/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.qualifier.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "mathStubImpl.hpp"

mathStubImpl::mathStubImpl() {

}

mathStubImpl::~mathStubImpl() {

}

void mathStubImpl::calc(const std::shared_ptr<CommonAPI::ClientId> clientId, int32_t num1, int32_t num2, v1_42::commonapi::someip::mathStub::calcReply_t _reply) {
    int32_t sum = num1 + num2;
    int32_t diff = num1 - num2;

    _reply(sum, diff);
}
