/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.qualifier.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#include <sstream>
#include <v1/commonapi/someip/methodSampleStubDefault.hpp>

class methodSampleStubImpl : public v1::commonapi::someip::methodSampleStubDefault {
public:
    methodSampleStubImpl();
    virtual ~methodSampleStubImpl();

    virtual void setName(const std::shared_ptr<CommonAPI::ClientId> clientId, std::string familyName, v1_0::commonapi::someip::methodSampleStub::setNameReply_t _reply);
};
