/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v201412051405.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "serializationStubImpl.hpp"

SampleStubImpl::SampleStubImpl() {

}

SampleStubImpl::~SampleStubImpl() {

}

void SampleStubImpl::setNameAttribute(v1::commonapi::serialization::Sample::Name value) {
    v1::commonapi::serialization::SampleStubDefault::setNameAttribute(value);
}
