name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: "Checkout capicxx-core-tools"
      uses: actions/checkout@v3 
      with:
        repository: COVESA/capicxx-core-tools
        path: capicxx-core-tools
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build dependency
      run: mvn -f org.genivi.commonapi.core.releng/pom.xml -D target.id=org.genivi.commonapi.core.target clean verify
      working-directory: capicxx-core-tools
      
    - name: Build project
      run: mvn -D COREPATH=capicxx-core-tools -f org.genivi.commonapi.someip.releng/pom.xml -D target.id=org.genivi.commonapi.someip.target clean verify
